[build]
  publish = "templates"
  command = "pip install -r requirements-netlify.txt"

[build.environment]
  PYTHON_VERSION = "3.9"
  PIP_CACHE_DIR = "/opt/build/cache/pip"

[[redirects]]
  from = "/api/chat/*"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/chatbot_app/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
