[build]
  publish = "templates"
  command = "echo 'Static build complete - no dependencies needed'"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[[redirects]]
  from = "/api/chat/*"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/chatbot_app/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  
[build.environment]
  SKIP_INSTALL = "true"
