[build]
  publish = "templates"
  command = "echo 'Static site with serverless functions ready'"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/chat/*"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/chatbot_app/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
