[build]
  publish = "templates"
  command = "./build.sh"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/django/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/chatbot_app/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
