
services:
  - type: web
    name: clang-ai-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start_production.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chatbot_project.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.11
