# Generated by Django 5.0.6 on 2025-08-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(max_length=200)),
                ('reaction', models.CharField(choices=[('helpful', 'Helpful'), ('not-helpful', 'Not Helpful'), ('love', 'Love'), ('copy', 'Copy'), ('share', 'Share')], max_length=20)),
                ('user_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
